### ISSUE TITLE
Change Button Icons

### ISSUE THREAD

**Issue by Webby1015** [Webby1015/Text-Editor#1]
This is What Buttons Currently look like 
![image](https://github.com/Webby1015/Text-Editor/assets/83869760/632c36ea-9c64-412e-aa76-a46ca398fd1e)
Expected should look something like these
![image](https://github.com/Webby1015/Text-Editor/assets/83869760/d39843a8-9d4a-45f6-a7c4-be41039f72d5)

**Comment by rohit-chaware** [comment]
Hey @Webby1015 can you assign this issue to me.

**Comment by Webby1015** [comment]
> Hey @Webby1015 can you assign this issue to me.

You can start working on this issue
