### ISSUE TITLE
Make this Text title Unselectable , i.e no one can highlight copy this text 

### ISSUE THREAD

**Issue by Webby1015** [Webby1015/Text-Editor#6]
![image](https://github.com/Webby1015/Text-Editor/assets/83869760/e89df0f6-1413-477a-9c44-18f2129f4353)

**Comment by Ahsan689** [comment]
hey @Webby1015 I want to contribute in this, please assign to me.

**Comment by Webby1015** [comment]
> hey @Webby1015 I want to contribute in this, please assign to me.

Sure you've been assigned this issue
